import type { Team, Review } from '../types';

export const SAMPLE_TEAMS: Team[] = [
  {
    id: 'team-woai-001',
    team_number: 'WOAI-001',
    team_name: 'NeuralVision Labs',
    problem_statement_id: 'PS-AI-04',
    problem_statement: 'Autonomous Micro-Ultrasound Image Segmentation for Rural Oncology Triaging using Quantized Edge Vision Transformers.',
    members: [
      { id: 'm-1', name: 'Aarav Sharma', email: 'aarav@neuralvision.ai', role: 'Team Lead' },
      { id: 'm-2', name: 'Priya Iyer', email: 'priya@neuralvision.ai', role: 'ML Engineer' },
      { id: 'm-3', name: 'Rohan Deshmukh', email: 'rohan@neuralvision.ai', role: 'Edge Systems' },
      { id: 'm-4', name: 'Ananya Verma', email: 'ananya@neuralvision.ai', role: 'Fullstack Dev' },
    ],
    is_demo: true,
    created_at: '2026-09-24T10:00:00Z',
    updated_at: '2026-09-24T10:00:00Z',
  },
  {
    id: 'team-woai-002',
    team_number: 'WOAI-002',
    team_name: 'AgriSense Autonomous',
    problem_statement_id: 'PS-AI-11',
    problem_statement: 'Hyperspectral Drone Imagery Processing for Multi-Crop Disease Early Warning and Variable Nitrogen Dispensation.',
    members: [
      { id: 'm-5', name: 'Vikramaditya Nair', email: 'vikram@agrisense.io', role: 'Lead Architect' },
      { id: 'm-6', name: 'Sneha Patel', email: 'sneha@agrisense.io', role: 'CV Researcher' },
      { id: 'm-7', name: 'Kabir Sengupta', email: 'kabir@agrisense.io', role: 'IoT Firmware' },
    ],
    is_demo: true,
    created_at: '2026-09-24T10:30:00Z',
    updated_at: '2026-09-24T10:30:00Z',
  },
  {
    id: 'team-woai-003',
    team_number: 'WOAI-003',
    team_name: 'QuantumGuard AI',
    problem_statement_id: 'PS-CYBER-02',
    problem_statement: 'Post-Quantum Lattice-Based Cryptographic Anomaly Detection in High-Frequency Zero-Trust Financial Backbones.',
    members: [
      { id: 'm-8', name: 'Divya Sundaram', email: 'divya@qguard.net', role: 'Security Lead' },
      { id: 'm-9', name: 'Arjun Mehra', email: 'arjun@qguard.net', role: 'Quantum Cryptography' },
      { id: 'm-10', name: 'Tanvi Joshi', email: 'tanvi@qguard.net', role: 'Backend Engineer' },
      { id: 'm-11', name: 'Aditya Rao', email: 'aditya@qguard.net', role: 'Frontend & UI' },
    ],
    is_demo: true,
    created_at: '2026-09-24T11:00:00Z',
    updated_at: '2026-09-24T11:00:00Z',
  },
  {
    id: 'team-woai-004',
    team_number: 'WOAI-004',
    team_name: 'CognitiveBio Engine',
    problem_statement_id: 'PS-BIO-09',
    problem_statement: 'De Novo Multi-Target Therapeutic Peptide Design using Graph Diffusion Networks and Molecular Dynamics Simulation.',
    members: [
      { id: 'm-12', name: 'Siddharth Roy', email: 'siddharth@cognibio.org', role: 'Bioinformatics Lead' },
      { id: 'm-13', name: 'Meera Nambiar', email: 'meera@cognibio.org', role: 'Deep Learning' },
      { id: 'm-14', name: 'Farhan Zaidi', email: 'farhan@cognibio.org', role: 'Simulation Engineer' },
    ],
    is_demo: true,
    created_at: '2026-09-24T11:30:00Z',
    updated_at: '2026-09-24T11:30:00Z',
  },
  {
    id: 'team-woai-005',
    team_number: 'WOAI-005',
    team_name: 'EchoGrid Intelligence',
    problem_statement_id: 'PS-ENERGY-07',
    problem_statement: 'Decentralized Smart Grid Demand-Response Orchestration via Multi-Agent Reinforcement Learning with Microgrid Islanding Support.',
    members: [
      { id: 'm-15', name: 'Gautam Menon', email: 'gautam@echogrid.com', role: 'Power Systems Lead' },
      { id: 'm-16', name: 'Ishita Kapoor', email: 'ishita@echogrid.com', role: 'RL Engineer' },
      { id: 'm-17', name: 'Raghav Trivedi', email: 'raghav@echogrid.com', role: 'Cloud Infrastructure' },
    ],
    is_demo: true,
    created_at: '2026-09-24T12:00:00Z',
    updated_at: '2026-09-24T12:00:00Z',
  },
];

export const SAMPLE_INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-001-1',
    team_id: 'team-woai-001',
    team_number: 'WOAI-001',
    review_number: 1,
    judge_id: 'judge-admin1',
    judge_username: 'admin1',
    scores: [
      { criterion_id: 'r1_c1', criterion_name: 'Problem Understanding & Clarity', score: 10, max_score: 10, comments: 'Superb grasp of rural oncology gaps.' },
      { criterion_id: 'r1_c2', criterion_name: 'Target User Identification', score: 9, max_score: 10, comments: 'Clear clinics and health worker workflow.' },
      { criterion_id: 'r1_c3', criterion_name: 'Ideology / Insight', score: 9, max_score: 10, comments: 'Quantized vision transformer approach is solid.' },
      { criterion_id: 'r1_c4', criterion_name: 'Uniqueness & Feasibility', score: 9, max_score: 10, comments: 'Low latency target is verified.' },
      { criterion_id: 'r1_c5', criterion_name: 'Technical Reasoning + Communication & Q/A', score: 9, max_score: 10, comments: 'Very articulate responses.' },
    ],
    total_score: 46,
    max_possible_score: 50,
    comments: 'Exceptional prelims pitch. Strong pipeline and well identified user constraints.',
    status: 'submitted',
    submitted_at: '2026-09-24T14:30:00Z',
    updated_at: '2026-09-24T14:30:00Z',
    is_locked: true,
  },
  {
    id: 'rev-001-2',
    team_id: 'team-woai-001',
    team_number: 'WOAI-001',
    review_number: 2,
    judge_id: 'judge-admin2',
    judge_username: 'admin2',
    scores: [
      { criterion_id: 'r2_c1', criterion_name: 'Functional Prototype', score: 10, max_score: 10, comments: 'Live edge deployment on Raspberry Pi demonstrated.' },
      { criterion_id: 'r2_c2', criterion_name: 'Technical Architecture', score: 9, max_score: 10, comments: 'Clean ONNX runtime integration.' },
      { criterion_id: 'r2_c3', criterion_name: 'Constraint Compliance', score: 10, max_score: 10, comments: 'Operates under 15W power ceiling.' },
      { criterion_id: 'r2_c4', criterion_name: 'Innovation & UX', score: 9, max_score: 10, comments: 'Intuitive tablet UI.' },
      { criterion_id: 'r2_c5', criterion_name: 'Performance + Security & Privacy', score: 9, max_score: 10, comments: 'On-device inferencing ensures patient privacy.' },
    ],
    total_score: 47,
    max_possible_score: 50,
    comments: 'Flawless mains demo. Real-time inference achieved on edge device.',
    status: 'submitted',
    submitted_at: '2026-09-24T16:45:00Z',
    updated_at: '2026-09-24T16:45:00Z',
    is_locked: true,
  },
  {
    id: 'rev-001-3',
    team_id: 'team-woai-001',
    team_number: 'WOAI-001',
    review_number: 3,
    judge_id: 'judge-admin3',
    judge_username: 'admin3',
    scores: [
      { criterion_id: 'r3_c1', criterion_name: 'Real-World Impact', score: 19, max_score: 20, comments: 'Huge societal value for remote healthcare.' },
      { criterion_id: 'r3_c2', criterion_name: 'Technical Depth', score: 18, max_score: 20, comments: 'Fine-tuned ViT backbone with pruning.' },
      { criterion_id: 'r3_c3', criterion_name: 'Innovation / Differentiation', score: 19, max_score: 20, comments: 'High novelty in tinyML quantization.' },
      { criterion_id: 'r3_c4', criterion_name: 'Scalability + Robustness Under Failure', score: 18, max_score: 20, comments: 'Offline fallback operational.' },
      { criterion_id: 'r3_c5', criterion_name: 'Business Feasibility + Crisis Response', score: 18, max_score: 20, comments: 'Clear NGO and hospital partner model.' },
    ],
    total_score: 92,
    max_possible_score: 100,
    comments: 'Grand Finale grade presentation. Production ready prototype.',
    status: 'submitted',
    submitted_at: '2026-09-25T11:20:00Z',
    updated_at: '2026-09-25T11:20:00Z',
    is_locked: true,
  },
  {
    id: 'rev-002-1',
    team_id: 'team-woai-002',
    team_number: 'WOAI-002',
    review_number: 1,
    judge_id: 'judge-admin1',
    judge_username: 'admin1',
    scores: [
      { criterion_id: 'r1_c1', criterion_name: 'Problem Understanding & Clarity', score: 9, max_score: 10 },
      { criterion_id: 'r1_c2', criterion_name: 'Target User Identification', score: 9, max_score: 10 },
      { criterion_id: 'r1_c3', criterion_name: 'Ideology / Insight', score: 9, max_score: 10 },
      { criterion_id: 'r1_c4', criterion_name: 'Uniqueness & Feasibility', score: 8, max_score: 10 },
      { criterion_id: 'r1_c5', criterion_name: 'Technical Reasoning + Communication & Q/A', score: 9, max_score: 10 },
    ],
    total_score: 44,
    max_possible_score: 50,
    comments: 'Strong presentation and agricultural sector domain knowledge.',
    status: 'submitted',
    submitted_at: '2026-09-24T15:00:00Z',
    updated_at: '2026-09-24T15:00:00Z',
    is_locked: true,
  },
  {
    id: 'rev-002-2',
    team_id: 'team-woai-002',
    team_number: 'WOAI-002',
    review_number: 2,
    judge_id: 'judge-admin2',
    judge_username: 'admin2',
    scores: [
      { criterion_id: 'r2_c1', criterion_name: 'Functional Prototype', score: 10, max_score: 10 },
      { criterion_id: 'r2_c2', criterion_name: 'Technical Architecture', score: 9, max_score: 10 },
      { criterion_id: 'r2_c3', criterion_name: 'Constraint Compliance', score: 9, max_score: 10 },
      { criterion_id: 'r2_c4', criterion_name: 'Innovation & UX', score: 9, max_score: 10 },
      { criterion_id: 'r2_c5', criterion_name: 'Performance + Security & Privacy', score: 9, max_score: 10 },
    ],
    total_score: 46,
    max_possible_score: 50,
    comments: 'Drone telemetry and spatial heatmaps worked cleanly.',
    status: 'submitted',
    submitted_at: '2026-09-24T17:15:00Z',
    updated_at: '2026-09-24T17:15:00Z',
    is_locked: true,
  },
  {
    id: 'rev-003-1',
    team_id: 'team-woai-003',
    team_number: 'WOAI-003',
    review_number: 1,
    judge_id: 'judge-admin2',
    judge_username: 'admin2',
    scores: [
      { criterion_id: 'r1_c1', criterion_name: 'Problem Understanding & Clarity', score: 9, max_score: 10 },
      { criterion_id: 'r1_c2', criterion_name: 'Target User Identification', score: 8, max_score: 10 },
      { criterion_id: 'r1_c3', criterion_name: 'Ideology / Insight', score: 9, max_score: 10 },
      { criterion_id: 'r1_c4', criterion_name: 'Uniqueness & Feasibility', score: 8, max_score: 10 },
      { criterion_id: 'r1_c5', criterion_name: 'Technical Reasoning + Communication & Q/A', score: 8, max_score: 10 },
    ],
    total_score: 42,
    max_possible_score: 50,
    comments: 'Quantum security math is strong, need to clarify performance overhead.',
    status: 'submitted',
    submitted_at: '2026-09-24T15:20:00Z',
    updated_at: '2026-09-24T15:20:00Z',
    is_locked: true,
  },
  {
    id: 'rev-003-2',
    team_id: 'team-woai-003',
    team_number: 'WOAI-003',
    review_number: 2,
    judge_id: 'judge-admin1',
    judge_username: 'admin1',
    scores: [
      { criterion_id: 'r2_c1', criterion_name: 'Functional Prototype', score: 8, max_score: 10 },
      { criterion_id: 'r2_c2', criterion_name: 'Technical Architecture', score: 8, max_score: 10 },
      { criterion_id: 'r2_c3', criterion_name: 'Constraint Compliance', score: 7, max_score: 10 },
      { criterion_id: 'r2_c4', criterion_name: 'Innovation & UX', score: 8, max_score: 10 },
      { criterion_id: 'r2_c5', criterion_name: 'Performance + Security & Privacy', score: 9, max_score: 10 },
    ],
    total_score: 40,
    max_possible_score: 50,
    comments: 'Draft scoring during prototype demonstration.',
    status: 'draft',
    updated_at: '2026-09-25T09:10:00Z',
    is_locked: false,
  },
  {
    id: 'rev-004-1',
    team_id: 'team-woai-004',
    team_number: 'WOAI-004',
    review_number: 1,
    judge_id: 'judge-admin3',
    judge_username: 'admin3',
    scores: [
      { criterion_id: 'r1_c1', criterion_name: 'Problem Understanding & Clarity', score: 9, max_score: 10 },
      { criterion_id: 'r1_c2', criterion_name: 'Target User Identification', score: 8, max_score: 10 },
      { criterion_id: 'r1_c3', criterion_name: 'Ideology / Insight', score: 9, max_score: 10 },
      { criterion_id: 'r1_c4', criterion_name: 'Uniqueness & Feasibility', score: 9, max_score: 10 },
      { criterion_id: 'r1_c5', criterion_name: 'Technical Reasoning + Communication & Q/A', score: 9, max_score: 10 },
    ],
    total_score: 44,
    max_possible_score: 50,
    comments: 'Deep biological knowledge and state-of-the-art diffusion approach.',
    status: 'submitted',
    submitted_at: '2026-09-24T15:45:00Z',
    updated_at: '2026-09-24T15:45:00Z',
    is_locked: true,
  },
];
